name: build
on:
  push:
  branch:
      - main
jobs:
  DigaOla:
    runs-on: ubunto-latest
    steps: 
      - run: echo "ola"
  Build:  
    runs-on: ubunto-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: '21'
          distruibuition: 'temurin'
          cache: 'gradle'
      - run: ./gradlew build