name: Build
on:
  push:
    branches:
      - main

jobs:
  DigaOla:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Diga ola
        uses: ./.github/actions/diga-ola-action

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4

      - name: Set Gradle Permission
        uses: ./.github/actions/set-gradlew-permission

      - name: Build Project
        uses: ./.github/actions/build-project
