name: Build
on:
    push:
        branches:
            - main
jobs:
    DigaOla:
        runs-on: ubuntu-latest
        steps:
            - uses: ./.github/actions/diga-ola-action
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v2
              with:
                java-version: '21'
                distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Set Gradle Permission
              run: chmod +x ./gradlew

            - run: ./gradlew build